name: inicioflutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:  
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  barcode_widget: ^2.0.2   
  toast: ^0.1.5
  fluttertoast: ^8.0.9
  http: ^0.13.3
  dio: ^4.0.0
  mysql1: ^0.20.0
  provider: ^6.0.3
  path_provider: ^2.0.11
  flutter_qr_bar_scanner: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
        - assets/ 
